.PHONY: all

all: src/Everything.agda
	agda src/Everything.agda

#FILE_FINDER:=find . -type f \( -name "*.agda" -o -name "*.lagda" \)
FILE_FINDER:=git ls-files "*.agda" "*.lagda"

EVERYTHING_CMD := \
	(cd "src"; \
	printf "module Everything where\n\n-- This autogenerated module imports everything in the project.\n\n"; \
	$(FILE_FINDER) \
		| sed 's,^\./,,g'           \
		| grep -v "Everything.agda" \
		| env LC_COLLATE=C sort     \
		| cut -c 1-                 \
		| cut -f1 -d'.'             \
		| sed 's/\//\./g'           \
		| sed 's/^/open import /'   \
	)

EVERYTHING_PATH := src/Everything.agda

EXISTING_EVERYTHING_CONTENTS:=$(shell cat $(EVERYTHING_PATH) 2>&1)
NEW_EVERYTHING_CONTENTS:=$(shell $(EVERYTHING_CMD))

ifneq ($(EXISTING_EVERYTHING_CONTENTS),$(NEW_EVERYTHING_CONTENTS))
.PHONY: src/Everything.agda
src/Everything.agda:
	$(EVERYTHING_CMD) > $@
endif
